# Generated by Django 5.2.2 on 2025-06-07 04:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('num_pages', models.PositiveIntegerField()),
                ('author', models.CharField(max_length=250)),
                ('publisher', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('language', models.CharField(max_length=250)),
                ('choices_genre', models.CharField(choices=[('drama', 'drama'), ('sci-fi', 'sci-fi'), ('romance', 'romance'), ('mystery', 'mystery'), ('history', 'history'), ('scientific', 'scientific'), ('other', 'other')], default='other', max_length=25)),
                ('publish', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_book', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='blog_book_created_01bb52_idx')],
            },
        ),
    ]
