# Generated by Django 5.2.2 on 2025-06-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_book_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('family', models.CharField(max_length=250)),
                ('massage', models.TextField()),
                ('email', models.EmailField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
            ],
        ),
    ]
